name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start

      - name: Pull Docker image to registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull kirancg/k8s
   
      - name: Deploy to Kubernetes cluster
        run: |
          kubectl apply -f deployment.yaml     
      - name: Get deployment status
        run: kubectl get deployments
      - name: Get pod status
        run: kubectl get pods
      - name: Get pod status
        run: kubectl get pods
      - name: Get pod status
        run: kubectl get pods   
      - name: Get pod status
        run: kubectl get pods 
      - name: Get pod status
        run: kubectl get pods  
      - name: Wait for pod status is Ready
        run: kubectl wait pods -n default -l run=k8s --for condition=Ready --timeout=120s
      - name: Get Services
        run: kubectl get svc

        

   


    
